[package]
name = "inline_issue_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
str_indices = { version = "0.1.0", path = "str_indices" }
